import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Bananas',
    description: 'A bunch of fresh, organic bananas.',
    price: 1.99,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Fruits',
    hint: 'bananas fruit',
  },
  {
    id: '2',
    name: 'Whole Milk',
    description: 'A gallon of fresh whole milk.',
    price: 3.49,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Dairy',
    hint: 'milk carton',
  },
  {
    id: '3',
    name: 'Artisan Bread',
    description: 'A loaf of freshly baked artisan bread.',
    price: 4.99,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Bakery',
    hint: 'bread loaf',
  },
  {
    id: '4',
    name: 'Free-Range Eggs',
    description: 'A dozen large free-range eggs.',
    price: 4.29,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Dairy',
    hint: 'eggs carton',
  },
  {
    id: '5',
    name: 'Avocado',
    description: 'A ripe and creamy avocado.',
    price: 1.5,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Fruits',
    hint: 'avocado fruit',
  },
  {
    id: '6',
    name: 'Cherry Tomatoes',
    description: 'A pint of sweet cherry tomatoes.',
    price: 2.99,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Vegetables',
    hint: 'tomatoes vegetable',
  },
  {
    id: '7',
    name: 'Chicken Breast',
    description: 'Lean and tender chicken breast.',
    price: 9.99,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Meat',
    hint: 'chicken meat',
  },
  {
    id: '8',
    name: 'Spinach',
    description: 'A bag of fresh baby spinach.',
    price: 3.29,
    imageUrl: 'https://picsum.photos/400/300',
    category: 'Vegetables',
    hint: 'spinach leaves',
  },
];
